version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: yugioh-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yugioh_db
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - yugioh-network

volumes:
  db_data:

networks:
  yugioh-network:
    driver: bridge
